version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit-scraper-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    networks:
      - scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  scraper-network:
    name: scraper-network
    driver: bridge

